optimizations

diff --git a/sbin/labl b/sbin/labl
--- a/sbin/labl
+++ b/sbin/labl
@@ -139,12 +139,10 @@ function ipValid() {
 
     debug "$FUNCNAME ip_address = $ip_address" 34
 
-    if ipv4Valid $ip_address; then
+    if ipcalc -cs "${ip_address}" &> /dev/null; then
         return 0
     else
-        if ipv6Valid $ip_address; then
-            return 0
-        fi
+        return 1
     fi
 
     return 1
@@ -159,20 +157,13 @@ function ipv4Valid() {
 
     local inet=${1}
 
-    if [[ ! "${inet}" == *"/"* ]]; then
-        # address without cidr bits
-        if [[ ${inet} =~ ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$ ]]; then
-            return 0
-        fi
+    if ipcalc -4 -cs "${inet}" &> /dev/null; then
+        return 0
     else
-        # address with cidr bits
-        if [[ ${inet} =~ ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$ ]]; then
-            return 0
-        fi
+        return 1
     fi
 
     return 1
-
 }
 
 # regex for IPv6 validation
@@ -184,16 +175,10 @@ function ipv6Valid() {
 
     local inet6=${1}
 
-    if [[ ! "${inet6}" == *"/"* ]]; then
-        # address without cidr bits
-        if [[ ${inet6} =~ ^s*((([0-9A-Fa-f]{1,4}:){7}([0-9A-Fa-f]{1,4}|:))|(([0-9A-Fa-f]{1,4}:){6}(:[0-9A-Fa-f]{1,4}|((25[0-5]|2[0-4]d|1dd|[1-9]?d)(.(25[0-5]|2[0-4]d|1dd|[1-9]?d)){3})|:))|(([0-9A-Fa-f]{1,4}:){5}(((:[0-9A-Fa-f]{1,4}){1,2})|:((25[0-5]|2[0-4]d|1dd|[1-9]?d)(.(25[0-5]|2[0-4]d|1dd|[1-9]?d)){3})|:))|(([0-9A-Fa-f]{1,4}:){4}(((:[0-9A-Fa-f]{1,4}){1,3})|((:[0-9A-Fa-f]{1,4})?:((25[0-5]|2[0-4]d|1dd|[1-9]?d)(.(25[0-5]|2[0-4]d|1dd|[1-9]?d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){3}(((:[0-9A-Fa-f]{1,4}){1,4})|((:[0-9A-Fa-f]{1,4}){0,2}:((25[0-5]|2[0-4]d|1dd|[1-9]?d)(.(25[0-5]|2[0-4]d|1dd|[1-9]?d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){2}(((:[0-9A-Fa-f]{1,4}){1,5})|((:[0-9A-Fa-f]{1,4}){0,3}:((25[0-5]|2[0-4]d|1dd|[1-9]?d)(.(25[0-5]|2[0-4]d|1dd|[1-9]?d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){1}(((:[0-9A-Fa-f]{1,4}){1,6})|((:[0-9A-Fa-f]{1,4}){0,4}:((25[0-5]|2[0-4]d|1dd|[1-9]?d)(.(25[0-5]|2[0-4]d|1dd|[1-9]?d)){3}))|:))|(:(((:[0-9A-Fa-f]{1,4}){1,7})|((:[0-9A-Fa-f]{1,4}){0,5}:((25[0-5]|2[0-4]d|1dd|[1-9]?d)(.(25[0-5]|2[0-4]d|1dd|[1-9]?d)){3}))|:)))(%.+)?s* ]]; then
-            return 0
-        fi
+    if ipcalc -4 -cs "${inet6}" &> /dev/null; then
+        return 0
     else
-        # address with cidr bits
-        if [[ ${inet6} =~ ^s*((([0-9A-Fa-f]{1,4}:){7}([0-9A-Fa-f]{1,4}|:))|(([0-9A-Fa-f]{1,4}:){6}(:[0-9A-Fa-f]{1,4}|((25[0-5]|2[0-4]d|1dd|[1-9]?d)(.(25[0-5]|2[0-4]d|1dd|[1-9]?d)){3})|:))|(([0-9A-Fa-f]{1,4}:){5}(((:[0-9A-Fa-f]{1,4}){1,2})|:((25[0-5]|2[0-4]d|1dd|[1-9]?d)(.(25[0-5]|2[0-4]d|1dd|[1-9]?d)){3})|:))|(([0-9A-Fa-f]{1,4}:){4}(((:[0-9A-Fa-f]{1,4}){1,3})|((:[0-9A-Fa-f]{1,4})?:((25[0-5]|2[0-4]d|1dd|[1-9]?d)(.(25[0-5]|2[0-4]d|1dd|[1-9]?d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){3}(((:[0-9A-Fa-f]{1,4}){1,4})|((:[0-9A-Fa-f]{1,4}){0,2}:((25[0-5]|2[0-4]d|1dd|[1-9]?d)(.(25[0-5]|2[0-4]d|1dd|[1-9]?d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){2}(((:[0-9A-Fa-f]{1,4}){1,5})|((:[0-9A-Fa-f]{1,4}){0,3}:((25[0-5]|2[0-4]d|1dd|[1-9]?d)(.(25[0-5]|2[0-4]d|1dd|[1-9]?d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){1}(((:[0-9A-Fa-f]{1,4}){1,6})|((:[0-9A-Fa-f]{1,4}){0,4}:((25[0-5]|2[0-4]d|1dd|[1-9]?d)(.(25[0-5]|2[0-4]d|1dd|[1-9]?d)){3}))|:))|(:(((:[0-9A-Fa-f]{1,4}){1,7})|((:[0-9A-Fa-f]{1,4}){0,5}:((25[0-5]|2[0-4]d|1dd|[1-9]?d)(.(25[0-5]|2[0-4]d|1dd|[1-9]?d)){3}))|:)))(%.+)?s*(\/(d|dd|1[0-1]d|12[0-8]))$ ]]; then
-            return 0
-        fi
+        return 1
     fi
 
     return 1
@@ -708,6 +693,7 @@ function lablInit() {
     Dependencies+=(dirname)
     Dependencies+=(find)
     Dependencies+=(ip)
+    Dependencies+=(ipcalc)
     Dependencies+=(ipset)
     Dependencies+=(printf)
     Dependencies+=(readlink)
@@ -984,12 +970,8 @@ function lablLoad() {
             debug "$FUNCNAME load_candidate = $load_candidate" 30
 
             local -i valid_load_candidate=1
-            if ipv4Valid "$load_candidate"; then
+            if ipValid "$load_candidate"; then
                 valid_load_candidate=0
-            else
-                if ipv6Valid "$load_candidate"; then
-                    valid_load_candidate=0
-                fi
             fi
 
             if [ $valid_load_candidate -eq 0 ]; then
@@ -1631,9 +1613,7 @@ function lablStatus() {
 
     if [ $Iptables_Flag -ne 0 ]; then
         if [ $labl_running -eq 0 ]; then
-            if [ $labl_inet_count -eq 0 ] && [ $labl_inet6_count -eq 0 ]; then
-                printf "labl is running\n\n"
-            else
+            if [ $labl_inet_count -ne 0 ] && [ $labl_inet6_count -ne 0 ]; then
                 if [ $IP6_Enabled -eq 0 ]; then
                     printf "$labl_inet6_blacklist_count blacklisted and $labl_inet6_whitelist_count whitelisted v6 IP addresses\n"
                 fi
@@ -1663,56 +1643,55 @@ function lablStatus() {
                 else
                     printf "\n"
                 fi
+            fi
 
-                # TODO debt; this part works but needs work.
-                if [ $Permanent_Flag -eq 0 ]; then
+            # TODO debt; this part works but needs work.
+            if [ $Permanent_Flag -eq 0 ]; then
 
-                    printf "[+]\n"
-                    printf "[+] Permanent (check); $Blacklist_Permanent_File\n"
-                    printf "[+]\n\n"
+                printf "[+]\n"
+                printf "[+] Permanent (check); $Blacklist_Permanent_File\n"
+                printf "[+]\n\n"
 
-                    if [ ! -d $(dirname "$Blacklist_Permanent_File") ]; then
-                        mkdir -p "$(dirname "$Blacklist_Permanent_File")" &> /dev/null
-                        if [ $? -ne 0 ]; then
-                            aborting "[ERROR] mkdir -p $(dirname "$Blacklist_Permanent_File") failed"
-                        fi
+                if [ ! -d $(dirname "$Blacklist_Permanent_File") ]; then
+                    mkdir -p "$(dirname "$Blacklist_Permanent_File")" &> /dev/null
+                    if [ $? -ne 0 ]; then
+                        aborting "[ERROR] mkdir -p $(dirname "$Blacklist_Permanent_File") failed"
                     fi
+                fi
 
-                    printf "\n"
+                printf "\n"
 
-                    local permanent_qualifiers=0
+                local permanent_qualifiers=0
 
-                    local ip_family
-                    for ip_family in ${IP_Families[@]}; do
-                        while read blacklist_ip; do
-                            if ipv4Valid $blacklist_ip; then
-                                local blacklist_qualifier=$(echo "$blacklist_ip" | awk -F\. '{print $1"."$2"."$3}')
-                                local blacklist_qualifier_count=$(ipset save ${Ipset_Name}_${ip_family} | grep -v nomatch$ | awk '{print $NF}' | grep ^${blacklist_qualifier}\. | wc -l)
-                                if [ $blacklist_qualifier_count -gt $Blacklist_Permanent_Max ]; then
-                                    if ! grep ^${blacklist_qualifier}.0/24 "$Blacklist_Permanent_File" &> /dev/null; then
-                                        _echo "# blacklisted ip = $blacklist_ip, qualifier $blacklist_qualifier currently has $blacklist_qualifier_count blacklisted which is >= $Blacklist_Permanent_Max" WARNING
-                                        echo "${blacklist_qualifier}.0/24" >> "${Blacklist_Permanent_File}"
-                                        if [ $? -eq 0 ]; then
-                                            _echo "# ${blacklist_qualifier}.0/24 added to $Blacklist_Permanent_File" NOTICE
-                                        else
-                                            _error "# ${blacklist_qualifier}.0/24 failed to add to $Blacklist_Permanent_File" ERROR
-                                        fi
-                                        let permanent_qualifiers=$permanent_qualifiers+1
+                local ip_family
+                for ip_family in ${IP_Families[@]}; do
+                    while read blacklist_ip; do
+                        if ipv4Valid $blacklist_ip; then
+                            local blacklist_qualifier=$(echo "$blacklist_ip" | awk -F\. '{print $1"."$2"."$3}')
+                            local blacklist_qualifier_count=$(ipset save ${Ipset_Name}_${ip_family} | grep -v nomatch$ | awk '{print $NF}' | grep ^${blacklist_qualifier}\. | wc -l)
+                            if [ $blacklist_qualifier_count -gt $Blacklist_Permanent_Max ]; then
+                                if ! grep ^${blacklist_qualifier}.0/24 "$Blacklist_Permanent_File" &> /dev/null; then
+                                    _echo "# blacklisted ip = $blacklist_ip, qualifier $blacklist_qualifier currently has $blacklist_qualifier_count blacklisted which is >= $Blacklist_Permanent_Max" WARNING
+                                    echo "${blacklist_qualifier}.0/24" >> "${Blacklist_Permanent_File}"
+                                    if [ $? -eq 0 ]; then
+                                        _echo "# ${blacklist_qualifier}.0/24 added to $Blacklist_Permanent_File" NOTICE
+                                    else
+                                        _error "# ${blacklist_qualifier}.0/24 failed to add to $Blacklist_Permanent_File" ERROR
                                     fi
+                                    let permanent_qualifiers=$permanent_qualifiers+1
                                 fi
                             fi
-                        done <<<  "$(ipset save ${Ipset_Name}_${ip_family} | grep -v nomatch$ | grep ^add | awk '{print $NF}' | grep -v \/ | sort -uV)"
-                    done
-                    unset -v ip_family
-
-                    if [ ${permanent_qualifiers} -le 0 ]; then
-                        _echo "permanent check completed; no qualifiers found" OK
-                    else
-                        if [ -w "${Blacklist_Permanent_File}" ]; then
-                            sort -uV "${Blacklist_Permanent_File}" -o "${Blacklist_Permanent_File}"
                         fi
-                    fi
+                    done <<<  "$(ipset save ${Ipset_Name}_${ip_family} | grep -v nomatch$ | grep ^add | awk '{print $NF}' | grep -v \/ | sort -uV)"
+                done
+                unset -v ip_family
 
+                if [ ${permanent_qualifiers} -le 0 ]; then
+                    _echo "permanent check completed; no qualifiers found" OK
+                else
+                    if [ -w "${Blacklist_Permanent_File}" ]; then
+                        sort -uV "${Blacklist_Permanent_File}" -o "${Blacklist_Permanent_File}"
+                    fi
                 fi
 
             fi
@@ -1721,7 +1700,9 @@ function lablStatus() {
         fi
     fi
 
-    ${table_exec} -L INPUT -n
+    if [ $Permanent_Flag -ne 0 ]; then
+        ${table_exec} -L INPUT -n
+    fi
 
     # clean up
     local ip_family
@@ -1908,20 +1889,19 @@ lablInit $@
 
 # supported options without other arguments are restart, start, status, stop
 
-# iptables is a special option, exit
-Iptables_Flag=1 # 0=true, 1=false
-if [ "$Option" == "iptables" ]; then
-    Start_Flag=0 # 0=true, 1=false
-    Status_Flag=0 # 0=true, 1=false
-    Iptables_Flag=0 # 0=true, 1=false
-    lablStart iptables
-    lablStatus iptables
-    exit
-fi
+# flags: 0=true, 1=false
+Add_Flag=1
+Check_Flag=1
+Iptables_Flag=1
+Permanent_Flag=1
+Remove_Flag=1
+Restart_Flag=1
+Save_Flag=1
+Start_Flag=1
+Status_Flag=1
+Stop_Flag=1
 
 # status is a special option, exit
-Permanent_Flag=1 # 0=true, 1=false
-Status_Flag=1 # 0=true, 1=false
 if [ "$Option" == "status" ]; then
     Status_Flag=0
     if [ "$2" == "permanent" ]; then
@@ -1933,8 +1913,17 @@ if [ "$Option" == "status" ]; then
     exit
 fi
 
+# iptables is a special option, exit
+if [ "$Option" == "iptables" ]; then
+    Start_Flag=0 # 0=true, 1=false
+    Status_Flag=0 # 0=true, 1=false
+    Iptables_Flag=0 # 0=true, 1=false
+    lablStart iptables
+    lablStatus iptables
+    exit
+fi
+
 # start is a special option, exit
-Start_Flag=1 # 0=true, 1=false
 if [ "$Option" == "start" ]; then
     Start_Flag=0 # 0=true, 1=false
     lablStart
@@ -1942,7 +1931,6 @@ if [ "$Option" == "start" ]; then
 fi
 
 # stop is a special option, exit
-Stop_Flag=1 # 0=true, 1=false
 if [ "$Option" == "stop" ]; then
     Stop_Flag=0 # 0=true, 1=false
     lablStop
@@ -1950,7 +1938,6 @@ if [ "$Option" == "stop" ]; then
 fi
 
 # restart is a special option, exit
-Restart_Flag=1 # 0=true, 1=false
 if [ "$Option" == "restart" ]; then
     Restart_Flag=0 # 0=true, 1=false
     lablStop
@@ -1958,14 +1945,12 @@ if [ "$Option" == "restart" ]; then
     exit
 fi
 
-Save_Flag=1 # 0=true, 1=false
 if [ "$Option" == "save" ]; then
     Save_Flag=0 # 0=true, 1=false
     lablSave "$IP_Address"
     exit
 fi
 
-Remove_Flag=1 # 0=true, 1=false
 # auto is super special, it requires lablStart but no IP validation
 Auto_Flag=1 # 0=true, 1=false
 if [ "$Option" == "auto" ]; then
@@ -1976,14 +1961,12 @@ else
     lablStart
 fi
 
-Add_Flag=1 # 0=true, 1=false
 if [ "$Option" == "add" ]; then
     Add_Flag=0 # 0=true, 1=false
     lablAdd "$IP_Address" "$Ipset_Mode"
     exit
 fi
 
-Check_Flag=1 # 0=true, 1=false
 if [ "$Option" == "check" ]; then
     Check_Flag=0 # 0=true, 1=false
     lablCheck "$IP_Address"
